# Generated by Django 4.2.14 on 2025-10-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_available', models.IntegerField(default=0)),
                ('received_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Inventory Batches',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the warehouse.', max_length=100, unique=True)),
                ('location', models.CharField(help_text='Physical address or location description.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(help_text='Quantity moved.')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (Receive)'), ('OUT', 'Stock Out (Consumption/Sale)'), ('TR', 'Transfer'), ('ADJ', 'Adjustment')], help_text='Type of movement (e.g., IN, OUT, Transfer).', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorybatch')),
                ('from_warehouse', models.ForeignKey(blank=True, help_text='Source warehouse for the movement. Null if stock is newly received.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse for the movement. Null if stock is consumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('AL', 'Aluminium'), ('GL', 'Glass'), ('SC', 'Screw'), ('GU', 'Glue'), ('RU', 'Rubber'), ('TO', 'Tools')], default='AL', help_text='The general type of the material (e.g., Aluminium, Glass).', max_length=2)),
                ('category', models.CharField(help_text='Category of the material (e.g., Metal Sheets, Adhesives).', max_length=50)),
                ('unit', models.CharField(help_text='Unit of measure (e.g., KG, PCS, M).', max_length=10)),
                ('size', models.CharField(blank=True, help_text='Dimensional size description (e.g., 4x8 ft).', max_length=50)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Thickness in mm or another relevant unit.', max_digits=5, null=True)),
                ('colour', models.CharField(blank=True, max_length=30)),
                ('current_stock', models.IntegerField(default=0, help_text='Total current quantity available across all batches/warehouses.')),
                ('reorder_level', models.IntegerField(default=0, help_text='Minimum stock level before a reorder is triggered.')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Raw Materials',
                'ordering': ['type_name'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.rawmaterial'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches', to='inventory.warehouse'),
        ),
    ]
