# Generated by Django 5.2.7 on 2025-12-06 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='reorder_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='type_name',
            field=models.CharField(choices=[('AL', 'Aluminium'), ('GL', 'Glass'), ('SC', 'Screw'), ('GU', 'Glue'), ('RU', 'Rubber'), ('TO', 'Tools')], default='AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (Receive)'), ('OUT', 'Stock Out (Consumption/Sale)'), ('TR', 'Transfer'), ('ADJ', 'Adjustment')], max_length=3),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='inventory.warehouse'),
        ),
    ]
