# Generated by Django 5.2.7 on 2025-12-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_options_stockmovement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Finished Products',
                'ordering': ['name'],
            },
        ),
    ]
