# Generated by Django 5.2.7 on 2025-12-06 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_options_stockmovement_created_by_and_more'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='expected_date',
            new_name='expected_delivery',
        ),
        migrations.RemoveField(
            model_name='goodsreceiveditem',
            name='batch_reference',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_from_pr',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='required_by',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='goodsreceiveditem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequestitem',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='grn_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='goodsreceived',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='goodsreceiveditem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_items', to='procurement.purchaseorderitem'),
        ),
        migrations.AlterField(
            model_name='goodsreceiveditem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
