# Generated by Django 5.2.7 on 2025-12-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('sales', '0002_delete_salesorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Linked sales order, if this WO was created to fulfil a sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='sales.salesorder'),
        ),
    ]
