# Generated by Django 5.2.7 on 2025-12-18 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_rawmaterial_current_stock_product'),
        ('production', '0002_workorder_sales_order'),
        ('sales', '0003_salesorder_assigned_to_alter_salesorder_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('machine', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='finishedproductbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productionoutput',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AlterModelOptions(
            name='bom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='finishedproductbatch',
            options={'ordering': ['-produced_date']},
        ),
        migrations.AlterModelOptions(
            name='productionstagelog',
            options={'ordering': ['stage__sequence_no']},
        ),
        migrations.AlterField(
            model_name='finishedproductbatch',
            name='qty_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finishedproductbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='productionstagelog',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='workorderconsumption',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorybatch'),
        ),
        migrations.AlterField(
            model_name='workorderconsumption',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product', 'version_no')},
        ),
        migrations.AlterUniqueTogether(
            name='productionstagelog',
            unique_together={('work_order', 'stage')},
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product', 'version_no'], name='production__product_7b19d5_idx'),
        ),
        migrations.AddIndex(
            model_name='productionstage',
            index=models.Index(fields=['sequence_no'], name='production__sequenc_7dc0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'created_at'], name='production__status_e16db5_idx'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_required__gt', 0)), name='bom_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_produced__gt', 0)), name='output_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='productionwastage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_wasted__gt', 0)), name='wastage_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='workorderconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='consumed_qty_positive'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.productionstage'),
        ),
        migrations.AddField(
            model_name='productiontask',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.workorder'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['status'], name='production__status_f37eff_idx'),
        ),
        migrations.AddIndex(
            model_name='productiontask',
            index=models.Index(fields=['stage'], name='production__stage_i_bf147c_idx'),
        ),
    ]
