# Generated by Django 4.2.14 on 2025-12-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role'),
        ('users', '0004_userprofile_must_change_password'),
    ]

    operations = [
    ]
