# Generated by Django 5.2.7 on 2025-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20251208_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('procurement', 'Procurement'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('production', 'Production'), ('qc', 'QC'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('employee', 'Employee'), ('sweeper', 'Sweeper')], default='admin', max_length=30),
        ),
    ]
