# Generated by Django 4.2.14 on 2025-12-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_team', to='users.userprofile')),
                ('members', models.ManyToManyField(blank=True, related_name='member_of_teams', to='users.userprofile')),
            ],
        ),
    ]
