# Generated by Django 5.2.7 on 2025-12-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_team_id_alter_team_manager_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('procurement', 'Procurement'), ('inventory', 'Inventory'), ('sales', 'Sales'), ('production', 'Production'), ('qc', 'QC'), ('manager', 'Manager'), ('finance', 'Finance'), ('employee', 'Employee'), ('sweeper', 'Sweeper')], default='admin', max_length=30),
        ),
    ]
