# Generated by Django 4.2.14 on 2025-12-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(help_text='ID of the task being inspected (will be linked later)')),
                ('inspection_type', models.CharField(choices=[('incoming', 'Incoming'), ('midline', 'Midline'), ('final', 'Final')], max_length=20)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('inspection_time', models.TimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
