# Generated by Django 5.2.7 on 2025-12-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrderItem',
        ),
    ]
