# Generated by Django 5.2.7 on 2025-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_assigned_to_alter_salesorder_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank='website', choices=[('website', 'Website'), ('referral', 'Referral'), ('walkin', 'Walk-in'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
    ]
