# Generated by Django 5.2.7 on 2025-12-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_source_alter_quotation_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_name',
            field=models.CharField(default='Manual Item', help_text='Enter item  (e.g. Door, Window)', max_length=200),
            preserve_default=False,
        ),
    ]
