# Generated by Django 5.2.7 on 2025-12-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_quotationitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='sales.quotation'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
